boot:
  location: location
  name: 随便什么
server:
  port: 9080
  servlet:
    context-path: /boot
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8'
    driver-class-name: 'com.mysql.jdbc.Driver'
    username: 'root'
    password: 'root'
  freemarker:
    cache: false #页面不加载缓存
  devtools:
    restart:
      enabled: true #启用热部署
  thymeleaf:
        cache: false
        encoding: UTF-8
        mode: HTML5
        servlet:
          content-type: text/html
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true